### ISSUE TITLE
Disable CCR link

### ISSUE THREAD

**Issue by cachedout** [elastic/stack-monitoring#21]
[copy/paste from email]

     In 6.6.0 BC3 gotten from the dev ticket here - https://github.com/elastic/dev/issues/1114 and the the git hub issues here:
I found a few open cloud issues to disable CCR for 6.6 and higher, the cloud team has now set the disabled flags and on BC3 build gotten from the 6.6.0 dev ticket.  I do see its gone from the management page. But from the monitoring page- when I click on overview- I do see CCR there. I checked in 6.5.0 too and I think its a separate app handled by monitoring team and it does show up. 

But in 6.6.0 there is no CCR or Remote cluster UI  its disabled in cloud - so my question is should the link be disabled in monitoring too ?

**Comment by rasroh** [comment]
cc @jen-huang

**Comment by rasroh** [comment]
Thanks @cachedout  for the update. I actually am confused by the milestone 6.6 label.

**Comment by cachedout** [comment]
@rasroh Apologies. That is a mistake on my part! I have changed the label.

**Comment by cachedout** [comment]
PR here: https://github.com/elastic/kibana/pull/28840
